FROM UPSTREAM_REPO

RUN apk update && apk add git bash

# Add vendorcheck for vendoring checks
RUN GOPATH=$GOPATH go get github.com/FiloSottile/vendorcheck
RUN GOPATH=$GOPATH go build -o /usr/local/bin/vendorcheck github.com/FiloSottile/vendorcheck

# Add govendor
RUN GOPATH=$GOPATH go get github.com/kardianos/govendor
RUN GOPATH=$GOPATH go build -o /usr/local/bin/govendor github.com/kardianos/govendor
