FROM UPSTREAM_REPO

MAINTAINER Randy Fay <rfay@drud.com>

RUN apk update && apk add git bash build-base

ENV GOTOOLSTOBUILD github.com/FiloSottile/vendorcheck github.com/kardianos/govendor github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck honnef.co/go/tools/cmd/unused github.com/kisielk/errcheck

RUN echo "GOTOOLSTOBUILD=$GOTOOLSTOBUILD"

RUN for item in $GOTOOLSTOBUILD; do echo "Adding tool $item" && go get $item && go build -o /usr/local/bin/$(basename $item) $item;  done